from distribution_metrics.approximate_patch_mmd import MMDApproximate
from distribution_metrics.patch_mmd import PatchMMD_RBF, PatchMMD_Inverse
from distribution_metrics.patch_swd import PatchSWDLoss
from distribution_metrics.patch_coherence_loss import PatchCoherentLoss
from distribution_metrics.sliced_coherence_loss import PatchCoherentSWDLoss